//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationDataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductWithDetailQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductWithDetailQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelationDataAccess.Resources.ProductWithDetailQueries", typeof(ProductWithDetailQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    ph.productId AS ProductId,
        ///    ph.name AS ProductName,
        ///    ph.price AS Price,
        ///    ph.subCategoryId AS SubCategoryId,
        ///    ph.produced AS Produced,
        ///    ph.store AS Store,
        ///    pd.ProductDetailId AS ProductDetailId,
        ///    pd.ProductId AS DetailProductId,
        ///    pd.shortDescription AS ShortDescription,
        ///    pd.imageUrl AS ImageUrl,
        ///    c.yearManifactured AS CarYearManufactured,
        ///    c.model AS CarModel,
        ///    c.serialNumber AS CarSerialNumber,
        ///    c.engineDisplacement AS CarEngineDisplacement,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductsWithDetailsByJoinOptimised {
            get {
                return ResourceManager.GetString("GetProductsWithDetailsByJoinOptimised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	SELECT 
        ///    ph.productId AS ProductId,
        ///    ph.name AS ProductName,
        ///    ph.price AS Price,
        ///    ph.subCategoryId AS SubCategoryId,
        ///    ph.produced AS Produced,
        ///    ph.store AS Store,
        ///    
        ///    -- Detalji proizvoda
        ///    (SELECT pd.ProductDetailId FROM ProductDetails pd WHERE ph.productId = pd.ProductId) AS ProductDetailId,
        ///    (SELECT pd.shortDescription FROM ProductDetails pd WHERE ph.productId = pd.ProductId) AS ShortDescription,
        ///    (SELECT pd.imageUrl FROM ProductDetails pd WHERE ph.productId = p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductsWithDetailsBySubQuery {
            get {
                return ResourceManager.GetString("GetProductsWithDetailsBySubQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    ph.productId AS ProductId,
        ///    ph.name AS ProductName,
        ///    ph.price AS Price,
        ///    ph.subCategoryId AS SubCategoryId,
        ///    ph.produced AS Produced,
        ///    ph.store AS Store,
        ///
        ///    pd.ProductDetailId AS ProductDetailId,
        ///    pd.shortDescription AS ShortDescription,
        ///    pd.imageUrl AS ImageUrl,
        ///
        ///
        ///	c.ProductDetailId AS CarDetailsId,
        ///    c.yearManifactured AS CarYearManufactured,
        ///    c.model AS CarModel,
        ///    c.serialNumber AS CarSerialNumber,
        ///    c.engineDisplacement AS CarEngineDisplaceme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductsWithDetailsBySubQueryApply {
            get {
                return ResourceManager.GetString("GetProductsWithDetailsBySubQueryApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    ph.productId AS ProductId,
        ///    ph.name AS ProductName,
        ///    ph.price AS Price,
        ///    ph.subCategoryId AS SubCategoryId,
        ///    ph.produced AS Produced,
        ///    ph.store AS Store,
        ///    pd.ProductDetailId AS ProductDetailId,
        ///    --pd.ProductId AS DetailProductId,
        ///    pd.shortDescription AS ShortDescription,
        ///    pd.imageUrl AS ImageUrl,
        ///    c.yearManifactured AS CarYearManufactured,
        ///    c.model AS CarModel,
        ///    c.serialNumber AS CarSerialNumber,
        ///    c.engineDisplacement AS CarEngineDisplacement, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProductWithDetailById {
            get {
                return ResourceManager.GetString("GetProductWithDetailById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM ProductsHeader ph LEFT JOIN ProductDetails pd ON (ph.productId=pd.ProductId)
        ///LEFT JOIN Cars c ON (c.ProductDetailId=pd.ProductDetailId)
        ///LEFT JOIN Devices d ON (d.ProductDetailId=pd.ProductDetailId) 
        ///LEFT JOIN Mobiles m ON (m.ProductDetailId=d.ProductDetailId)
        ///LEFT JOIN Laptops l ON (pd.ProductDetailId=l.ProductDetailId)
        ///LEFT JOIN Movies mo ON (mo.ProductDetailId=pd.ProductDetailId)
        ///.
        /// </summary>
        internal static string GetProductWithDetailsLeftJoin {
            get {
                return ResourceManager.GetString("GetProductWithDetailsLeftJoin", resourceCulture);
            }
        }
    }
}
